name: Build vlmcsd for OpenWrt
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openwrt/sdk:ath79-generic
      options: --user root
    steps:
      - name: Build
        run: |
          # 1. Сначала удалим всё лишнее, чтобы начать с чистого листа
          rm -rf *
          
          # 2. Клонируем исходники прямо в корень рабочей папки
          git clone https://github.com/Wind4/vlmcsd.git .
          
          # 3. Проверка: видим ли мы Makefile в текущей папке?
          echo "Содержимое текущей папки:"
          ls -F
          
          # 4. Собираем
          # CC автоматически определен в SDK, просто используем make
          make clean
          make CC=mips-openwrt-linux-musl-gcc CFLAGS="-static -Os -D_GNU_SOURCE" LDFLAGS="-static" vlmcsd
          
          # 5. Проверяем, где лежит файл
          echo "Файл vlmcsd:"
          ls -l bin/vlmcsd

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: vlmcsd-mips-openwrt
          path: bin/vlmcsd
